export const safetyFilePattern = /(?:^|\/)(?:auth|security|permission|permissions|secret|secrets|credential|database|db|payment|payments|validator|validation|schema|middleware|guards?)(?:\/|\.|$)|(?:^|\/)(?:\.github\/workflows|\.circleci|\.buildkite)(?:\/|$)|(?:^|\/)(?:dockerfile|jenkinsfile|azure-pipelines\.ya?ml)$/i
export const safetySurfaceFilePattern = /(?:^|\/)(?:auth|security|permission|permissions|credential|secret|secrets|session|oauth|jwt|csrf|validator|validation|schema|middleware|guards?|sanitiz(?:er|ation)?|serializ(?:er|ation)?|deserializ(?:er|ation)?|database|db|query|sql|command|shell|upload|filesystem|crypto|encryption)(?:\/|\.|$)/i
export const safetySurfacePatchPattern = /(?:\b(?:eval|child_process|exec|spawn)\s*\(|\binnerHTML\s*=|dangerouslySetInnerHTML|\b(?:SELECT|INSERT|UPDATE|DELETE)\b[^;\n]{0,120}(?:\+|\.|\$\{|format\s*\()|real_escape_string|\b(?:fetch|axios|request|readFile|writeFile|deserialize|unserialize|JSON\.parse|validate|sanitize|escape|authorize|permission|fallback|rateLimit|csrf|safeParse|parseInt|parseFloat|getenv|process\.env|throw new|try|catch)\b|\b(?:bypassAuthorization|bypassAuth|skipAuthorization|skipAuth)\s*\(|\b[\w$]*(?:api[_-]?key|secret|password|token)\b)/i
export const confirmedRiskPatchPattern = /(?:\b(?:eval|child_process|exec|spawn)\s*\(|\binnerHTML\s*=|dangerouslySetInnerHTML|\b[\w$]*(?:api[_-]?key|secret|password|token)\s*[:=]|\b(?:bypassAuthorization|bypassAuth|skipAuthorization|skipAuth)\s*\(|\bSELECT[^;\n]{0,120}(?:\+|\.|\$\{|format\s*\())/i
export const confirmedDefensivePatchPattern = /(?:real_escape_string|\b(?:validate|sanitize|escape|authorize|permission|fallback|rateLimit|csrf|safeParse|parseInt|parseFloat|getenv|process\.env)\b|\b(?:try|catch)\s*\{|\bthrow\s+new\b)/i
export const safetyPatchPattern = safetySurfacePatchPattern
export const safetyTestFilePattern = /(?:^|\/)(?:__tests__|tests?|specs?)(?:\/|$)|(?:^|\/)(?:test|spec)[-_][^/]+$|\.(?:test|spec)\.[^.]+$/i
export const safetyDocumentationFilePattern = /(?:^|\/)(?:docs?|documentation|guides?)(?:\/|$)|(?:^|\/)(?:readme|changelog|contributing)(?:\.[^.]+)?$/i
export const generatedSafetyFilePattern = /(?:^|\/)(?:node_modules|vendor|dist|build|coverage|\.next|\.nuxt)(?:\/|$)|(?:^|\/)(?:package-lock\.json|pnpm-lock\.yaml|yarn\.lock|bun\.lockb|minified|generated)/i
